service: devutils-worker

frameworkVersion: '4'

custom:
  wsgi:
    app: app.app

provider:
  name: aws
  runtime: python3.12

functions:
  api:
    handler: wsgi_handler.handler
    events:
      - httpApi: '*'

plugins:
  - serverless-wsgi
  - serverless-python-requirements
