service: devutils-worker

frameworkVersion: '3'

custom:
  wsgi:
    app: app.app

useDotenv: true

provider:
  name: aws
  runtime: python3.9

functions:
  api:
    handler: wsgi_handler.handler
    events:
      - httpApi: '*'
    environment:
      S3_BUCKET: ${env:S3_BUCKET}
      AWS_S3_BUCKET_REGION: ${env:AWS_S3_BUCKET_REGION}

plugins:
  - serverless-wsgi
  - serverless-python-requirements
